yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.Author.as_view(), name='author'),
    path('tech/', views.Tech.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edition'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),

]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied_view'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.fields.related import ForeignKey

from groups.models import Group

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста в поле выше',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата поста',
    )
    author = ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста',
    )
    group = ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа поста',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        verbose_name='Картинка',
        help_text='Выберите картинку',
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария в поле выше',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата поста',
    )
    post = ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        blank=True,
        null=True,
        verbose_name='Комментарий',
        help_text='Комментарий поста'
    )
    author = ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий пользователя',
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self) -> str:
        return self.text[:15]


class Following(models.Model):
    user = ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Подписан',
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self) -> str:
        return self.user.username

yatube/posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Post, Comment

User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        exclude = ('author',)
        labels = {
            "text": 'Текст поста',
            "group": "Группа поста"
        }
        help_texts = {
            'text': 'Введите текст поста в поле выше',
            'group': 'Выберите группу, к которой будет относиться пост',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', ]
        exclude = ('author', 'post', )
        labels = {
            "text": 'Текст комментария',
        }
        help_texts = {
            'text': 'Введите текст комментария в поле выше',
        }

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from . import forms
from .models import Following, Group, Post

User = get_user_model()


def index(request):
    template = 'posts/index.html'
    page_title = 'Главная страница Yatube'
    title = 'Последние обновления на сайте'
    posts = Post.objects.order_by('-pub_date')
    paginator = Paginator(posts, settings.POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': title,
        'page_title': page_title,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    title = group.title
    page_title = title
    posts = group.posts.all().order_by('-pub_date')
    paginator = Paginator(posts, settings.POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group_slug': slug,
        'page_obj': page_obj,
        'group_title': title,
        'page_title': page_title,
        'group': group
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    user_c = get_object_or_404(User, username=username)
    posts = user_c.posts.all().order_by('-pub_date')
    paginator = Paginator(posts, settings.POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    posts_total = posts.count()
    user_name = f'{user_c.first_name} {user_c.last_name}'
    title = f'Профайл пользователя {user_name}'
    following = False
    print(request.user.following.filter(), request.user.username)
    for author in request.user.following.all():
        if user_c == User.objects.get(username=author):
            following = True
    context = {
        'title': title,
        'page_obj': page_obj,
        'posts_total': posts_total,
        'user_name': user_name,
        'author': user_c,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    group = post.group
    author = f'{post.author.first_name} {post.author.last_name}'
    date = post.pub_date
    posts_count = post.author.posts.count()
    title = f'Пост {post.text[:30]}'
    username = post.author.username
    post_author = post.author
    text = post.text
    comments = post.comments
    form = form = forms.CommentForm(request.POST or None)
    context = {
        'title': title,
        'author': author,
        'group': group,
        'date': date,
        'posts_count': posts_count,
        'username': username,
        'text': text,
        'post_id': post_id,
        'post': post,
        'post_author': post_author,
        'comments': comments,
        'form': form
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = forms.PostForm(request.POST or None, request.FILES)
    if not form.is_valid():
        context = {
            'form': form,
            'request': request,
        }
        return render(request, template, context)
    else:
        form_obj = form.save(commit=False)
        form_obj.author = request.user
        form_obj.save()
        return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request, post_id):
    post_obj = get_object_or_404(Post, pk=post_id)
    template = 'posts/create_post.html'
    form = forms.PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post_obj,
    )
    context = {
        'is_edit': True,
        'form': form
    }
    if request.user != post_obj.author:
        return redirect('posts:post_detail', post_id=post_id)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    else:
        return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = Post.objects.get(pk=post_id)
    form = forms.CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    page_title = 'Лента подписок'
    title = 'Лента подписок'
    posts = Post.objects.order_by('-pub_date').filter(author=request.user)
    paginator = Paginator(posts, settings.POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    subs = [author for author in request.user.following.all()]
    print('!!! -', subs)
    print(request.user.follower.all(), request.user.following.all(), Following.objects.filter(author))
    context = {
        'page_obj': page_obj,
        'title': title,
        'page_title': page_title,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = User.objects.get(username=username)
    Following.objects.create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = User.objects.get(username=username)
    Following.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
  {% if is_edit %}
    Редактирование поста
  {% else %}
    Новый пост
  {% endif %} 
  {% endblock title %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактирование поста
                {% else %}
                  Новый пост
                {% endif %}             
              </div>
              <div class="card-body">        
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}       
                  {% for field in form %} 
                    <div class="form-group row my-3">
                      <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                          {% if field.field.required %}
                            <span class="required text-danger">*</span>
                          {% endif %}
                      </label>
                      {{ field|addclass:'form-control' }} 
                        {% if field.help_text %}
                          <small 
                            id="{{ field.id_for_label }}-help"
                            class="form-text text-muted"
                          >
                            {{ field.help_text|safe }}
                          </small>
                        {% endif %}
                    </div>
                  {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %} 
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
    {% block content %}
      <div class="container py-5">     
        <h1>{{ title }}</h1>
        {% cache 1 index_page %}
        {% include 'posts/includes/switcher.html' %}
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text|safe }}
          </p>
          {% if post.group is not None %}
            <p>
              <a href="{% url 'posts:group_list' post.group.slug %}">Все посты группы</a>
            </p>
          {% endif %}
          <p>
            <a href="{% url 'posts:profile' post.author %}">Все посты автора</a>
          </p>
          <p>
            <a href="{% url 'posts:post_detail' post.pk %}">Подробнее</a>
          </p>
        </article>
          {% if not forloop.last %}
            <hr>
          {% endif %}
        {% endfor %}
        {% endcache %}
        {% include 'includes/paginator.html' %}
      </div>  
  {% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
      <div class="container py-5">
        <h1>
            {{ group.title }}
        </h1>
        <p>
            {{ group.description }}
        </p>
        {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.first_name }} {{ post.author.last_name }},
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}      
            <p>
              {{ post.text|safe }}
            </p>
            <p>
            <a href="{% url 'posts:post_detail' post.pk %}">Читать полностью</a>
            </p>
            <p>
            {% if request.user == post.author %}
              <p>
                <a href="{% url 'posts:post_edition' post.pk %}">
                  Редактировать пост
                </a>
              </p>
            {% endif %}      
          </article>
          {% if not forloop.last %}
            <hr>
          {% endif %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
      </div>
  {% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
    {% block content %}
      <div class="container py-5">     
        <h1>{{ title }}</h1>
        {% cache 20 index_page %}
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text|safe }}
          </p>
          {% if post.group is not None %}
            <p>
              <a href="{% url 'posts:group_list' post.group.slug %}">Все посты группы</a>
            </p>
          {% endif %}
          <p>
            <a href="{% url 'posts:profile' post.author %}">Все посты автора</a>
          </p>
          <p>
            <a href="{% url 'posts:post_detail' post.pk %}">Подробнее</a>
          </p>
        </article>
          {% if not forloop.last %}
            <hr>
          {% endif %}
        {% endfor %}
        {% endcache %}
        {% include 'includes/paginator.html' %}
      </div>  
  {% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% load thumbnail %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
<div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ date|date:"d E Y" }} 
            </li>
            {% if group %}
              <li class="list-group-item">
                Группа: {{ group }}
                <a href="{% url 'posts:group_list' group.slug %}">
                  все записи группы
                </a>
              </li>
              {% endif %}
              <li class="list-group-item">
                Автор: {{ author }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ posts_count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' username %}">
                все посты пользователя
              </a>
            </li>
            {% if request.user == post_author %}
              <li class="list-group-item">
                <a href="{% url 'posts:post_edition' post_id %}">
                  редактировать пост
                </a>
              </li>
          {% endif %}
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
           {{ text|safe }}
          </p>
          {% if user.is_authenticated %}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post.id %}">
                  {% csrf_token %}      
                  <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
            </div>
          {% endif %}
          {% for comment in comments.all %}
            <div class="media mb-4">
              <div class="media-body">
                <h5 class="mt-0">
                  <a href="{% url 'posts:profile' comment.author %}">
                    {{ comment.author.username }}
                  </a>
                  ({{ comment.author.first_name }} {{ comment.author.last_name }})
                </h5>
                <p>
                  {{ comment.text }}
                </p>
              </div>
            </div>
          {% endfor %}
        </article>
      </div> 
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
<div class="container py-5">        
        <h1>Все посты пользователя {{ user_name }} </h1>
        <h3>Всего постов: {{ posts_total }} </h3>
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
        {% endif %}   
        {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.first_name }} {{ post.author.last_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %} 
            <p>
              {{ post.text|safe }}
            </p>       
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>  
          </article>
          {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group }}</a> 
          {% endif %}
          {% if not forloop.last %}
            <hr>
          {% endif %}
          {% endfor %}
        {% include 'includes/paginator.html' %} 
</div>
{% endblock content %}